Description: Device Measurements Populator Application
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  targetCluster:
    Type: String
    Description: ECS Cluster name within which this application should be run
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  devicesTableName:
    Type: String
    Description: DynamoDB Table Name to store devices
  productDescriptorsTableName:
    Type: String
    Description: DynamoDB Table Name to store product descriptors
  deviceFileDataBucket:
    Type: String
    Description: S3 Bucket Name to store measured device files
  expireFileDataTable:
    Type: String
    Description: DynamoDb table referencing measured device files due for removal
  productDescriptorsTableIndex:
    Type: String
    Description: DynamoDb index of product descriptors
  albTargetGroupArn:
    Type: String
    Description: Target Group ARN for device details api
Resources:
  taskDefinitionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: deviceMeasurementsPopulatorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - :545349016803:table/
                    - !Ref 'expireFileDataTable'
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - :545349016803:table/
                    - !Ref 'devicesTableName'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - :545349016803:table/
                    - !Ref 'productDescriptorsTableName'
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - :545349016803:table/
                    - !Ref 'productDescriptorsTableName'
                    - /index/
                    - !Ref 'productDescriptorsTableIndex'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref 'deviceFileDataBucket'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref 'deviceFileDataBucket'
                      - /*
  taskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt 'taskDefinitionRole.Arn'
      ContainerDefinitions:
        - Name: device-measurements-populator
          Cpu: '1'
          Essential: 'true'
          Image: !Join
            - ''
            - - 'docker.io/linn/device-measurements-populator:'
              - !Ref 'dockerTag'
          Memory: '100'
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: DEVICES_TABLE_NAME
              Value: !Ref 'devicesTableName'
            - Name: PRODUCT_DESCRIPTORS_TABLE_NAME
              Value: !Ref 'productDescriptorsTableName'
            - Name: PRODUCT_DESCRIPTORS_TABLE_INDEX
              Value: !Ref 'productDescriptorsTableIndex'
            - Name: EXPIRE_S3_OBJECTS_TABLE_NAME
              Value: !Ref 'expireFileDataTable'
            - Name: DEVICE_FILE_DATA_BUCKET
              Value: !Ref 'deviceFileDataBucket'
            - Name: NODE_ENV
              Value: release
            - Name: PORT
              Value: '3000'
  service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'targetCluster'
      DesiredCount: '1'
      TaskDefinition: !Ref 'taskDefinition'
      Role: ecsServiceRole
      LoadBalancers:
        - ContainerName: device-measurements-populator
          ContainerPort: 3000
          TargetGroupArn: !Ref 'albTargetGroupArn'
